---
language: java
jdk:
- oraclejdk7
- openjdk6
- openjdk7
env:
  global:
  - secure: JlFTItSTHxmevCoX1fXWkXtQOqP8ERT5ndeYMc378acqZIWEpmoSQelP8unRjtU6sU/4dxdUWpEFLrbcNQsFuPsgzMLGSwuEcjbuSBGMgdAHXSl6+FfBWrCcde2WIfk+eYMm7mrhcySWMvtWss1kDOu+s8+HtRvnRCAsfz+77hs=
script: mvn package site site:stage -q -ff -B
before_install:
- chmod -R 777 ./travis/init-travis-build.sh
- "./travis/init-travis-build.sh"
after_success:
- chmod -R 777 ./travis/push-javadoc-to-gh-pages.sh
- "./travis/push-javadoc-to-gh-pages.sh"
